// export const foodItems =
//     [
//         {
//             time:15,
//             id: 1,
//             name: 'pizza',
//             discription: 'Place tomato slices in a circle on crust, overlapping slightly until crust is completely covered. Drizzle with olive oil. ... Cover with olives if desired, green pepper and onion. Sprinkle with basil.',
//             src:'./Images/pizza.jpg',
//             prise: 30,
//             ingredients:['1 and 1/3 cups (320ml) warm water (between 100-110°F, 38-43°C)',
//                         '2 and 1/4 teaspoons Red Star Platinum instant yeast (1 standard packet)*',
//                         '1 Tablespoon (13g) granulated sugar',
//                         '2 Tablespoons (30ml) olive oil',
//                         '3/4 teaspoon salt',
//                         '3 and 1/2 cups (438g) all-purpose flour (spoon & leveled), plus more for hands and surface',
//                         'sprinkle of cornmeal for dusting the pan'
//         ]
//         },
//         {
//             time:12,
//             id: 2,
//             name: 'roll',
//             discription: 'Spring rolls are filled with minced vegetables, seafood, poultry, or meat, folded into a food wrapper made from dough or rice paper that is rolled after being folded and is then baked, deep fried, or steamed. ',
//             src:'./Images/roll.jpg',
//             prise: 25,
//             ingredients:['200 gm chopped into cubes chicken','1 medium chopped tomato','1/2 pinch red chilli powder','2 tablespoon vegetable oil',
//                         '1/2 cut into strips cucumber','1/2 tablespoon chopped coriander leaves','1 large thinly sliced onion',                        '2 medium chopped green chilli',
//                         '2 pinches garam masala powder',
//                         '1 lemon wedges',
//                         '1 teaspoon tomato ketchup',
//                         '1 tablespoon green chilli sauce']
//         },
//         {
//             time:30,
//             id: 3,
//             name: 'samosa',
//             discription: 'Typically triangular in shape, a semi-circular sheet of wheat flour pastry, such as filo, is crafted into a cone before a forkful of aromatic filling is shovelled inside. Then, a thick mixture of flour and water seals the final edge to create the iconic three-point shape',
//             src:'./Images/samosa.jpg',
//             prise: 10,
//             ingredients:['2 cup all purpose flour',
//                 '1 teaspoon cumin seeds',
//                 '1 teaspoon crushed ginger',
//                 '1 teaspoon raisins',
//                 '5 boiled potato',
//                 '1 teaspoon coriander powder',
//                 '1 teaspoon red chilli powder',
//                 '1 teaspoon kasoori methi leaves',
//                 '1 teaspoon carom seeds',
//                 '1/4 cup water',
//                 '2 cup refined oil',
//                 '1/2 teaspoon coriander seeds',
//                 '1 teaspoon green chilli',
//                 '1 teaspoon cashews',
//                 '1 teaspoon cumin powder',
//                 '1/2 teaspoon garam masala powder',
//                 'salt as required',
//                 '1 teaspoon coriander leaves',
//                 '2 tablespoon ghee',
//                 '1 handful raw peanuts']
//         },
//         {
//             time:10,
//             id: 4,
//             name: 'maggi',
//             discription: 'MAGGI is the most loved instant noodles that has appealed to people of all age groups. Ready in just a few minutes, MAGGI is always open to interesting recipes and combinations with other dishes',
//             src:'./Images/maggi.jpg',
//             prise: 10,
//             ingredients:['2 tbsp oil',
//                 '2 clove garlic (finely chopped)',
//                 '1 inch ginger (finely chopped)',
//                 '1 chilli (slit)',
//                 '½ onion (sliced)',
//                 '2 tbsp spring onion (chopped)',
//                 '½ carrot (chopped)',
//                 ',¼ green capsicum (chopped)',
//                 ',5 snow pea (chopped)',
//                 ',5 beans (chopped)',
//                 ',¼ red capsicum (chopped)',
//                 ',5 florets broccoli',
//                 ',3 tbsp cabbage (shredded)',
//                 ',2 tbsp tomato sauce',
//                 ',1 tbsp soy sauce',
//                 ',1 tbsp vinegar',
//             ',1 tbsp chilli sauce',
//             ',¼ tsp pepper powder',
//             ',½ tsp salt',]
//         },
//         {
//             time:5,
//             id: 5,
//             name: 'hamburger',
//             discription: 'he exact origin of the hamburger may never be known with any certainty. Most historians believe that it was invented by a cook who placed a Hamburg steak between two slices of bread in a small town in Texas, and others credit the founder of White Castle for developing the "Hamburger Sandwich." Records from that time are scarce, however.',
//             src:'./Images/burger.jpg',
//             prise: 25,
//             ingredients:['1 pound ground lamb',
//                 '1/2 cup cooked white rice',
//                 '1 large egg, beaten',
//                 '1/2 cup chopped cilantro',
//                 'Kosher salt',
//                 'Freshly ground black pepper',
//                 '1/4 cup extra-virgin olive oil, plus more for grilling',
//                 '4 hot green chiles, such as serranos or jalapeños, thinly sliced',
//                 '2 mild green chiles, such as Anaheim or yellow wax chiles, seeded and coarsely chopped',
//                 '2 scallions, coarsely chopped',
//                 '1 garlic clove, smashed',
//                 'Warm naan, chopped tomatoes and feta, for serving',]
//         },
//         {
//             time:40,
//             id: 6,
//             name: 'egg',
//             discription: 'This dish includes boiling long enough for the yolk to become solid ("hard boiled") or just long enough for the albumin (egg white) to solidify ("soft boiled"). A similar result may be achieved by steaming the eggs rather than boiling.',
//             src:'./Images/egg.jpg',
//             prise: 19,
//             ingredients:[],

//         },
//         {
//             time:35,
//             id: 7,
//             name: 'Kalakki',
//             discription: '“Kalakki” in Tamil means “to mix”. It is a soft scrambled egg with a little curry added into it. Kalakki is a famous food from southern Tamil Nadu. But nowadays Kalakki has become a very sought after dish in many restaurants all over Tamilnadu.',
//             src:'./Images/egg-2.jpg',
//             prise:59,
//             ingredients:[],
//         },
//         {
//             time:60,
//             id: 8,
//             name: 'chicken',
//             discription: 'is a type of siu mei. Unlike most other meats in the siu mei category, this particular dish is not roasted; it is cooked in water or broth.',
//             src:'./Images/chikan.jpg',
//             prise: 19,
//             ingredients:['1 (1¾-pound/800-gram) chicken, skinned and cut into 12 pieces',
//                 '¼ cup (50 ml) vegetable oil',
//                 '1-inch (2½-cm) cinnamon stick',
//                 '4 or 5 cloves',
//                 '4 or 5 green cardamom pods',
//                 '4 medium red onions, grated',
//                 '1 tablespoon fresh ginger paste',
//                 '1 tablespoon fresh garlic paste',
//                 '½ teaspoon ground turmeric',
//                 '1½ tablespoons ground coriander',
//                 '1½ teaspoons ground roasted cumin (see Notes)',
//                 '1 teaspoon red chile powder',
//                 '4 medium tomatoes, puréed',
//                 '1½ teaspoons table salt',
//                 '1 teaspoon garam masala',
//                 '1 tablespoon chopped fresh cilantro'],
//         },
//         {
//             time:35,
//             id: 9,
//             name: 'RARE',
//             discription: 'RARE Womens Synthetic a-line Knee-Long Dress',
//             src:'./Images/wd1.jpg',
//             prise:59,
//             ingredients:[],
//         },

//     ]

export const foodItems = [
    {
        time: 4.1,
        id: 1, name: 'RARE',
        discription: 'This product is made from polyester and finished in an attractive blue color. It features printed pattern, half sleeve, V-neck, and is targeted towards women. Furthermore, it is recommended to be kept away from extreme heat, fire and corrosive liquids to avoid any form of damage.',
        src: './Images/wd1.jpg',
        prise: 59,
        ingredients: [
            'Package Dimensions : 32.5 x 25.1 x 5.4 cm; 430 Grams',
            'Date First Available : 31 July 2018',
            'Manufacturer  :  Epic Brands Pvt Ltd',
            'ASIN :  B07NTC2QLB',
            'Item model number  :  ep3153--m',
            'Country of Origin  :  India',
            'Department :  Women',
            'Manufacturer  : Epic Brands Pvt Ltd',
            'Packer  :  EPIC BRANDS PVT LTD, D-19, FIRST FLOOR OKHLA, DELHI-110020  9711060049',
            'Item Weight :  430 g',
            'Included Components  :  1 Dress',
            'Generic Name  :  Dress',
        ],
    },
    {
        time: 3.5,
        id: 2,
        name: 'Amayra',
        discription: 'Flaunt sartorial elegance wearing Black coloured dress by Amayra. Look classy and stylish in this piece and revel in the comfort of the soft rayon fabric.',
        src: './Images/wd2.jpg',
        prise: 49,
        ingredients: [
            'Is Discontinued By Manufacturer :  No',
            'Package Dimensions :  34.5 x 16.7 x 6.5 cm; 250 Grams',
            'Date First Available :  28 November 2018',
            'Manufacturer  :  Amayra',
            'ASIN  :  B07KYGQZ3C',
            'Item part number  :  dress',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Amayra',
            'Item Weight  :  250 g',
        ],
    },
    {
        time: 4.5,
        id: 3,
        name: 'GRITSTONES',
        discription: 'Gritstones brings to you this Stylish Kurta which is made from cotton fabric and comes i 2 different colors to choose from. This Kurta has been designed keeping in mind the latest trends in contemporary casual fashion.',
        src: './Images/md3.jpg',
        prise: 56,
        ingredients: [
            'Package Dimensions  :  31.8 x 30.7 x 3.7 cm; 260 Grams',
            'Date First Available  :  18 October 2019',
            'Manufacturer  :  Gritstones',
            'ASIN  :  B07Z9FNYJD',
            'Item part number  :  GSFSKUT2385ANTHR_S',
            'Department  :  Men',
            'Manufacturer  :  Gritstones',
            'Item Weight  :  260 g',
            'Best Sellers Rank: #57,081 in Clothing & Accessories (See Top 100 in Clothing & Accessories)',
        ],
    },
    {
        time: 3.8,
        id: 4,
        name: 'Diverse',
        discription: 'Diverse is a western wear value brand for men. Our range consists of basic and updated basic apparel across both formal and casual wear. We offer the right blend of quality, style and value aimed to delight our customers.',
        src: './Images/md4.jpg',
        prise: 89,
        ingredients: [
            'Package Dimensions  :  24.2 x 23.7 x 5.9 cm; 300 Grams',
            'Date First Available  :  7 April 2020',
            'Manufacturer  :  Diverse',
            'ASIN  :  B079TQ5GYX',
            'Item model number  :  DVF01F2L02-526E',
            'Country of Origin  :  India',
            'Department  :  Men',
            'Manufacturer  :  Diverse',
            'Item Weight  :  300 g',
            'Generic Name  :  Formal Shirt',
            'Best Sellers Rank: #378 in Clothing & Accessories',
        ],
    },
    {
        time: 4.7,
        id: 5,
        name: 'Diverse Mens Slim fit Formal Shirt',
        discription: 'Crafted in a cotton poly stretch fabric, this long-sleeved, slim-fit modern shirt offers superb comfort and an impeccable finish.',
        src: './Images/md5.jpg',
        prise: 102,
        ingredients: [
            'Date First Available  :  21 March 2020',
            'Product Dimensions  :  24 x 22 x 5 cm; 300 Grams',
            'Manufacturer  :  Shakti Brandz',
            'ASIN  :  B0867FK3WX',
            'Item model number  :  DCMFF28SC14L06-3767B',
            'Department  :  Men',
            'Manufacturer  :  Shakti Brandz, SHAKTIBRANDZ , No. 47, 1st Cross, Muniswamappa Layout Hosur Road, Near KPN Travel,', 'Bommanahalli-560068, Bangalore',
            'Item Weight  :  300 g',
            'Item Dimensions LxWxH  :  24 x 22 x 5 Centimeters',
            'Generic Name  :  Formal Shirt',
            'Best Sellers Rank: #236,574 in Clothing & Accessories',
        ],
    },
    {
        time: 4,
        id: 6,
        name: 'OORA',
        discription: `OORA Men's Waist Coat/Jacket Relaxed Casual Blazer`,
        src: './Images/md6.jpg',
        prise: 65,
        ingredients: [
            'Is Discontinued By Manufacturer  :  No',
            'Product Dimensions  :  20 x 11 x 3 cm; 400 Grams',
            'Date First Available  :  21 August 2018',
            'Manufacturer  :  A S INTERNATIONAL',
            'ASIN  :  B07GRC23M7',
            'Item model number  :  Tuxedo-NavyBlue-S',
            'Department  :  Men',
            'Manufacturer  :  A S INTERNATIONAL, 150, Preet Vihar, Ajnala Road, Amritsar-143001',
            'Packer  :  150, Preet Vihar, Ajnala Road, Amritsar-143001',
            'Item Weight  :  400 g',
            'Item Dimensions LxWxH  :  20 x 11 x 3 Centimeters',
            'Net Quantity  :  1.00 count',
            'Generic Name  :  Blazer',
            'Best Sellers Rank: #3,196 in Clothing & Accessories',
        ],
    },
]
export const women = [
    {
        time: 4,
        id: 11,
        name: 'Harpa',
        discription: `Slip into this trendy and attractive dress from Harpa and look stylish effortlessly. Made to accentuate any body type, it will give you that extra oomph and make you stand out wherever you are. Keep the accessories minimal for that added elegant `,
        src: './Images/w1.jpg',
        prise: 49,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },
    {
        time: 4.6,
        id: 12,
        name: 'Harpa',
        discription: `Navy Blue printed woven maxi dress with tie-up detail on the back, has a V-neck, sleeveless, an attached lining, flared hem. `,
        src: './Images/w2.jpg',
        prise: 49,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },
    {
        time: 4.9,
        id: 13,
        name: 'RARE',
        discription: `This product is made from polyester and finished in an attractive blue color. It features printed pattern, half sleeve, V-neck, and is targeted towards women. Furthermore, it is recommended to be kept away from extreme heat, fire and corrosive liquids to avoid any form of damage. `,
        src: './Images/w3.jpg',
        prise: 69,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },
    {
        time: 4.9,
        id: 14,
        name: 'ILLI LONDON ',
        discription: `Spruce up your wardrobe with this Dress from ILLI LONDON available on Amazon. This A-Line Dress has Solids as pattern type and is perfect for a day out with friends or a night of get-togethers with family.`,
        src: './Images/w4.jpg',
        prise: 79,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },
    {
        time: 4.5,
        id: 15,
        name: 'StyleStone ',
        discription: `This is a Women's Chiffon Tie up Rainbow Print Maxi Midi Dress by StyleStone`,
        src: './Images/w5.jpg',
        prise: 99,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },
    {
        time: 4.5,
        id: 16,
        name: 'SIRIL',
        discription: `Fabric: Crepe, Stylish Dress, Value for money
        Dress Work: Printed | Dress Sleeves: Half Sleeve
        Dress Color: Black, Beige`,
        src: './Images/w6.jpg',
        prise: 59,
        ingredients: [
            'Product Dimensions  :  35.6 x 25.4 x 5.8 cm; 300 Grams',
            'Date First Available  :  10 May 2017',
            'Manufacturer  :  Harpa',
            'ASIN  : B071VLM94J',
            'Item model number  :  GR3747C',
            'Country of Origin  :  India',
            'Department  :  Women',
            'Manufacturer  :  Harpa, B-107, Vishkarma Colony Surajkund Crossing M.B Road New Delhi-44, Contact # 011-65662221,', 'E-mail - info@harpa.in',
            'Packer :  Harpa Retail Private Limited, C58/1, Okhla Industrial Area, Okhla Phase II, New Delhi - 110020 Phone: ', '011-65662221',
            'Item Weight : 300 g',
            'Item Dimensions LxWxH  :  35.6 x 25.4 x 5.8 Centimeters',
            'Generic Name  :  Dress',
            'Best Sellers Rank: #153 in Clothing & Accessories ,',
        ],
    },


]

export const men = [
    {
        time: 4.6,
        id: 21,
        name: 'London Hills',
        discription: `The best in class, pure cotton regular fit round neck full sleeve, multi-purpose badge t-shirts. Great to wear at gym, sports club, family reunion, picnic or parties. Best part, never fades in color even if you wear and sleep during the night`,
        src: './Images/m1.jpg',
        prise: 102,
        ingredients: [
            'Product Dimensions  :  7 x 15 x 4 cm; 200 Grams',
            'Date First Available  :  30 November 2019',
            'ASIN  :  B0825YTRY4',
            'Item part number  :  LH_T_465_NAVY_CLUB_LOGO_SIZE_M',
            'Country of Origin  :  India',
            'Department  :  Men',
            'Item Weight  : 200 g',
            'Item Dimensions LxWxH  :  7 x 15 x 4 Centimeters',
            'Best Sellers Rank: #36, 110 in Clothing & Accessories, ',
        ],
    },
    {
        time: 4.3,
        id: 22,
        name: 'YHA',
        discription: `Crafted in a pure cotton fabric, this long-sleeved, regular-fit modern shirt offers superb comfort and a flawless finish. A reliable option for business wear, the shirt features a modern Kent collar, a curved bottom hem and a chest patch pocket. Team with tailored trousers and blazer for a pared-back professional look.`,
        src: './Images/m2.jpg',
        prise: 43,
        ingredients: [
            'Product Dimensions  :  7 x 15 x 4 cm; 200 Grams',
            'Date First Available  :  30 November 2019',
            'ASIN  :  B0825YTRY4',
            'Item part number  :  LH_T_465_NAVY_CLUB_LOGO_SIZE_M',
            'Country of Origin  :  India',
            'Department  :  Men',
            'Item Weight  : 200 g',
            'Item Dimensions LxWxH  :  7 x 15 x 4 Centimeters',
            'Best Sellers Rank: #36, 110 in Clothing & Accessories, ',
        ],
    },
    {
        time: 3.9,
        id: 23,
        name: 'EVOQ',
        discription: `EVOQ works with the pulse of what the man today needs - what his lifestyle is, and how we can be a sublime part of his world - every single day. EVOQ is what you turn to - no matter the occasion. EVOQ carries you from work to play, is in your wallet and is what you carry your essentials in`,
        src: './Images/m3.jpg',
        prise: 59,
        ingredients: [
            'Product Dimensions  :  7 x 15 x 4 cm; 200 Grams',
            'Date First Available  :  30 November 2019',
            'ASIN  :  B0825YTRY4',
            'Item part number  :  LH_T_465_NAVY_CLUB_LOGO_SIZE_M',
            'Country of Origin  :  India',
            'Department  :  Men',
            'Item Weight  : 200 g',
            'Item Dimensions LxWxH  :  7 x 15 x 4 Centimeters',
            'Best Sellers Rank: #36, 110 in Clothing & Accessories, ',
        ],
    },
    {
        time: 4,
        id: 24,
        name: 'Dennis Lingo',
        discription: `This Casual Solid shirt has a Mandarin / Chinese collar, full button Placket, Long Sleeves, and a curved hemline`,
        src: './Images/m4.jpg',
        prise: 59,
        ingredients: [
            'Product Dimensions  :  30 x 24 x 1 cm; 220 Grams',
            'Date First Available  :  19 March 2021',
            'Manufacturer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400050',
            'ASIN  :  B08ZKSLNQ1',
            'Item model number  :  AZ201_B-GREEN_S',
            'Department  :  Men',
            'Manufacturer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400050,', 'Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400032',
            'Packer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400015',
            'Item Weight  : 220 g',
            'Item Dimensions LxWxH  :  30 x 24 x 1 Centimeters',
            'Net Quantity  :  1.00 count',
            'Generic Name  :  Shirt',
            'Best Sellers Rank: #40 in Clothing & Accessories',
        ],
    },
    {
        time: 5,
        id: 25,
        name: 'WearIndia',
        discription: `Winter is naughty in many layers, so keep it out of your system with this colourful 100 % cotton hooded sweatshirts from the High Hill. Combining the ease of acrylic with this regular-fit sweatshirt with attached hooded will add grace to your look. Pair it with a jeans/trousers/chinos and this utterly soft sweater will make other guys go green with envy`,
        src: './Images/m5.jpg',
        prise: 79,
        ingredients: [
            'Product Dimensions  :  30 x 24 x 1 cm; 220 Grams',
            'Date First Available  :  19 March 2021',
            'Manufacturer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400050',
            'ASIN  :  B08ZKSLNQ1',
            'Item model number  :  AZ201_B-GREEN_S',
            'Department  :  Men',
            'Manufacturer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400050,', 'Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400032',
            'Packer  :  Swastik Creation -Gala no.B-21,Bharat Industrial estate, T.J. Road, Sewree (w) ,Mumbai - 400015',
            'Item Weight  : 220 g',
            'Item Dimensions LxWxH  :  30 x 24 x 1 Centimeters',
            'Net Quantity  :  1.00 count',
            'Generic Name  :  Shirt',
            'Best Sellers Rank: #40 in Clothing & Accessories',
        ],
    },


]

export const child = [
    {
        time: 5,
        id: 31,
        name: 'Urban Flu',
        discription: `Ideal For: BABY BOYS AND BABY GIRLS. Material Type : Cotton. Casual and Party wear`,
        src: './Images/c1.jpg',
        prise: 29,
        ingredients: [
            'Package Dimensions  :  37.7 x 24.7 x 5.9 cm; 470 Grams',
            'Date First Available  :  3 November 2020',
            'Manufacturer  :  Urban Flu',
            'ASIN  :  B08ML7RGYJ',
            'Item part number  :  DYellow7-8',
            'Country of Origin  :  India',
            'Department  :  Girls',
            'Manufacturer  :  Urban Flu',
            'Item Weight  :  470 g',
        ],
    },
    {
        time: 4.9,
        id: 32,
        name: 'YAYAVAR',
        discription: `Ultra Trend is a brand which deals in kids dresses as in Gowns, girls Frocks and cotton. Our motive is to provide best products at reasonable price. So buy this dress for your little princess to make her feel special this festive season thank you`,
        src: './Images/c3.jpg',
        prise: 26,
        ingredients: [
            'Package Dimensions  :  37.7 x 24.7 x 5.9 cm; 470 Grams',
            'Date First Available  :  3 November 2020',
            'Manufacturer  :  Urban Flu',
            'ASIN  :  B08ML7RGYJ',
            'Item part number  :  DYellow7-8',
            'Country of Origin  :  India',
            'Department  :  Girls',
            'Manufacturer  :  Urban Flu',
            'Item Weight  :  470 g',
        ],
    },
    {
        time: 4.9,
        id: 33,
        name: 'ULTRA TREND',
        discription: `Latest YAYAVAR Festive Collection, Made only fore your princess, Grab it before any one else.`,
        src: './Images/c2.jpg',
        prise: 25,
        ingredients: [
            'Package Dimensions  :  37.7 x 24.7 x 5.9 cm; 470 Grams',
            'Date First Available  :  3 November 2020',
            'Manufacturer  :  Urban Flu',
            'ASIN  :  B08ML7RGYJ',
            'Item part number  :  DYellow7-8',
            'Country of Origin  :  India',
            'Department  :  Girls',
            'Manufacturer  :  Urban Flu',
            'Item Weight  :  470 g',
        ],
    },
    {
        time: 4.8,
        id: 34,
        name: 'YAYAVAR',
        discription: `Latest YAYAVAR Festive Collection, Made only fore your princess, Grab it before any one else.`,
        src: './Images/c4.jpg',
        prise: 19,
        ingredients: [
            'Package Dimensions  :  37.7 x 24.7 x 5.9 cm; 470 Grams',
            'Date First Available  :  3 November 2020',
            'Manufacturer  :  Urban Flu',
            'ASIN  :  B08ML7RGYJ',
            'Item part number  :  DYellow7-8',
            'Country of Origin  :  India',
            'Department  :  Girls',
            'Manufacturer  :  Urban Flu',
            'Item Weight  :  470 g',
        ],
    },

]